### PR TITLE
Allow using IAM token by defining 'AWS_SESSION_TOKEN' in wp-config.php.

### PR DESCRIPTION
**Pull request by klakegg**

### CODE REVIEW

**Comment by polevaultweb** [comment]
@klakegg you can use the filter on the next line `aws_get_client_args` to pass the session token

**Comment by polevaultweb** [comment]
@klakegg out of interest what is the need for the token here? Does it provide a further level of security? How is it generated?

**Comment by klakegg** [comment]
It simply makes it easier and more obvious on how to configure IAM when in position to put the token directly into the wp-config.php.

**Comment by polevaultweb** [comment]
Sure. But what is the use case for using the token over just an IAM users access key and secret?

**Comment by klakegg** [comment]
The token is required to be able to use the IAM role temporary access key and secret.

**Comment by klakegg** [comment]
"When you make a call using temporary security credentials, the call must include a session token, which is returned along with those temporary credentials. AWS uses the session token to validate the temporary security credentials."
Source: http://docs.aws.amazon.com/STS/latest/UsingSTS/using-temp-creds.html

**Comment by polevaultweb** [comment]
Thanks. Although it seems counter intuitive to define temporary credentials in constants for a site, you would need to keep updating wp-config.php when they expire right?

**Comment by mitchmac** [comment]
I ran into the need for this when using the plugin on AWS Lambda. On Lambda the token is an environment variable, so there's no need to be updating wp-config.php, just need a line like:

```
define( 'AWS_SESSION_TOKEN', getenv('AWS_SESSION_TOKEN') );
```

And rather than needing a patch to the plugin, adding a filter for _aws_get_client_args_ from a plugin does the trick:

```
add_filter( 'aws_get_client_args', 'serverlesswp_filter_aws_args' );

function serverlesswp_filter_aws_args($args) {
	if (defined('AWS_SESSION_TOKEN')) {
		$args['token'] = AWS_SESSION_TOKEN;
	}
	return $args;
}
```

**Comment by ianmjones** [comment]
Thanks @mitchmac.

Closing this PR as the above example (https://github.com/deliciousbrains/wp-amazon-web-services/pull/64#issuecomment-359296641) is a nice way of adding this functionality should you need it.

I'll also point out that you can use the [AWS_USE_EC2_IAM_ROLE](https://deliciousbrains.com/wp-offload-s3/doc/iam-roles/) define in some scenarios.

**Pull request closed without merging**
